### ISSUE TITLE
Reproducing paper benchmarks

### ISSUE THREAD

**Issue by sachaservan** [cryptimeleon/upb.crypto.clarc#14]
Hi, I'm trying to run the CLARC benchmarks but it seems to be slower than expected given Table 3 [in the paper.](https://eprint.iacr.org/2018/835.pdf).

For example, I'm getting that it took **~18s, 763ms** to verify (5 in Table 3) when it should be taking **~0s, 170 ms**.   

For context, I'm running on a 2019 MacBook pro:
`./gradlew  test --tests de.upb.crypto.clarc.acs.PerformanceTest`

Any ideas for what could be going wrong here? 

Thanks!

**Comment by JanBobolz** [comment]
Hey,

we offer two kinds of pairing groups, (1) a built-in (pretty inefficient) Java pairing group, and (2) a [wrapper for the much faster mcl](https://github.com/cryptimeleon/mclwrap).
For the paper, we used the latter, but the code in this repository defaults to the former (so that it can be easily run without having to install additional external C++ libraries).

Now unfortuntely (at least for this request), we have reworked all of our library and completely broke the API that Clarc depended on. The same is true for our wrapper `mclwrap` for (2). So to make that work, we will have to find the right (old, compatible) version of `mclwrap` and of `mcl`. 

We can probably find the appropriate old versions so that the benchmarks can be reproduced. Maybe give us a week for that, you've caught us at a busy time 🙈.

Sorry for the inconvenience.

**Comment by sachaservan** [comment]
Ah I see, makes sense. I had a hunch it wasn't using mcl but given the readme didn't have any information on this I was hoping it was something dumb on my end.

**Comment by JanBobolz** [comment]
Hi,

with the [new commit](https://github.com/cryptimeleon/upb.crypto.clarc/commit/fb06a31f52bbdc5784dfc77e5fc8e81072d41d25) you should now be able to just run the `./install_mcl.sh` script and then future runs of clarc should use the new mcl pairing.

I've also pushed a Dockerfile to make this more easily reproducible.

**Comment by sachaservan** [comment]
Thanks a lot for the speedy response and fix. It's working now!

If anyone else is running this on MacOS, you need to move the ```jawt_md.h``` and ```jni_md.h``` 
from 
`/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/include/darwin` 
to 
`/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/include`. 

Otherwise `./install_mcl.sh` will fail.
